#!/bin/sh

echo "Compiling the testPRU.c application"
clpru --silicon_version=3 testPRU.c -z AM3359_PRU.cmd -o testPRU.out -m testPRU.map

echo "Converting the executable to a ARM object file"
hexpru bin.cmd testPRU.out

echo "Compiling the testBBB.c application"
gcc testBBB.c -o load_data -lpthread -lprussdrv


