#!/bin/sh

echo "Compiling the testPRU.c application"
clpru -i /usr/share/ti/cgt-pru/lib/ --silicon_version=3 dac.c -z AM3359_PRU.cmd -o dac -m dac.map 

echo "Converting the executable to a ARM object file"
hexpru bin.cmd dac.out

echo "Compiling the testBBB.c application"
gcc load_data.c -o load_data -lpthread -lprussdrv


